namespace FrenchAdjectives.AllConstants;

public partial class Constants
{
    public const string Excessif = "excessif";
    public const string Electrique = "électrique";
    public const string Eternel = "éternel";
    public const string Encombrant = "encombrant";
    public const string Emblematique = "emblématique";
    public const string Entetante = "entêtante";
    public const string Extreme = "extrême";
    public const string Environnant = "environnant";
    public const string Egale = "égale";
    public const string Energique = "énergique";
    public const string Enorme = "énorme";
    public const string Ecrit = "écrit";
    public const string Excite = "excité";
    public const string Excitee = "excitée";
    public const string Epais = "épais";
    public const string Etrange = "étrange";
    public const string Evident = "évident";
    public const string Excellent = "excellent";
    public const string Exotique = "exotique";
    public const string Extraordinaire = "extraordinaire";
    public const string Exuberant = "exubérant";
    public const string Elegant = "élégant";
    public const string Emouvant = "émouvant";
    public const string Enchanteur = "enchanteur";
    public const string Ensoleille = "ensoleillé";
    public const string Enthousiaste = "enthousiaste";
    public const string Ephemere = "éphémère";
    public const string Equitable = "équitable";
    public const string Essentiel = "essentiel";
    public const string Esthetique = "esthétique";
    public const string Ethique = "éthique";
    public const string Etonnant = "étonnant";
    public const string Euphorique = "euphorique";
    public const string Evocateur = "évocateur";
    public const string Extravagant = "extravagant";
    public const string Espagnol = "espagnol";
    public const string Eclaire = "éclairé";
    public const string Eclatant = "éclatant";
    public const string Efficace = "efficace";
    public const string Effrayant = "effrayant";
    public const string Elabore = "élaboré";
    public const string Embarrassant = "embarrassant";
    public const string Eminent = "éminent";
    public const string Empathique = "empathique";
    public const string Endurant = "endurant";
    public const string Engage = "engagé";
    public const string Envieux = "envieux";
    public const string Epuisant = "épuisant";
    public const string Equilibre = "équilibré";
    public const string Erudit = "érudit";
    public const string Estimable = "estimable";
}
