using FrenchAdjectives.AllConstants;

namespace FrenchAdjectives.AllAdjectiveRepository;

internal static partial class AdjectiveRepository
{
    public static readonly IReadOnlyList<string> D = new[]
    {
        Constants.Desoriente,
        Constants.Douce,
        Constants.Digne,
        Constants.Desole,
        Constants.Depenaille,
        Constants.Docile,
        Constants.Dangereux,
        Constants.Dispensable,
        Constants.Droite,
        Constants.Delicat,
        Constants.Difficile,
        Constants.Drole,
        Constants.Different,
        Constants.Doux,
        Constants.Durable,
        Constants.Dynamique,
        Constants.Decisif,
        Constants.Defiant,
        Constants.Desirable,
        Constants.Determine,
        Constants.Devoue,
        Constants.Divin,
        Constants.Domestique,
        Constants.Dramatique,
        Constants.Diligent,
        Constants.Discret,
        Constants.Distinctif,
        Constants.Distrayant,
        Constants.Documente,
        Constants.Dolent,
        Constants.Douteux,
        Constants.Draconien,
        Constants.Dubitatif,
        Constants.Dulcissime,
        Constants.Disponible,
        Constants.Desireux,
        Constants.Desireuse,
        Constants.Debordant,
        Constants.Deconcertant,
        Constants.Defavorable,
        Constants.Delirant,
        Constants.Dense,
        Constants.Deprimant,
        Constants.Desastreux,
        Constants.Desinvolte,
        Constants.Desordonne,
        Constants.Detestable,
        Constants.Devastateur,
        Constants.Discutable,
        Constants.Dominant,
        Constants.Depaysant,
        Constants.Demesure,
    };

    public static readonly IReadOnlyList<string> D_Popular = new[]
    {
        Constants.Drole,
        Constants.Doux,
        Constants.Dynamique,
        Constants.Determine,
        Constants.Devoue,
        Constants.Diligent,
        Constants.Discret,
        Constants.Disponible,
        Constants.Decisif,
        Constants.Defiant,
        Constants.Dangereux,
        Constants.Difficile,
        Constants.Dramatique,
        Constants.Dominant,
        Constants.Deprimant,
        Constants.Desastreux,
        Constants.Desinvolte,
        Constants.Deconcertant,
        Constants.Dubitatif,
        Constants.Dense,
    };
}
