using FrenchAdjectives.AllConstants;

namespace FrenchAdjectives.AllAdjectiveRepository;

internal static partial class AdjectiveRepository
{
    public static readonly IReadOnlyList<string> C = new[]
    {
        Constants.Calamiteux,
        Constants.Concret,
        Constants.Commun,
        Constants.Climatique,
        Constants.Coriace,
        Constants.Chaleureux,
        Constants.Colerique,
        Constants.Cru,
        Constants.Competent,
        Constants.Culpable,
        Constants.Compatissant,
        Constants.Contournable,
        Constants.Contextuelle,
        Constants.Corrompu,
        Constants.Crasseux,
        Constants.Cense,
        Constants.Celebre,
        Constants.Convulsif,
        Constants.Certain,
        Constants.Critique,
        Constants.Calme,
        Constants.Complet,
        Constants.Chaud,
        Constants.Cher,
        Constants.Court,
        Constants.Cruel,
        Constants.Clair,
        Constants.Complique,
        Constants.Celibataire,
        Constants.Courageux,
        Constants.Curieux,
        Constants.Creatif,
        Constants.Content,
        Constants.Complexe,
        Constants.Chaque,
        Constants.Condescendant,
        Constants.Capable,
        Constants.Capricieux,
        Constants.Charmant,
        Constants.Chronique,
        Constants.Civique,
        Constants.Clandestin,
        Constants.Coherent,
        Constants.Colossal,
        Constants.Confiant,
        Constants.Conscient,
        Constants.Constant,
        Constants.Contemplatif,
        Constants.Courant,
        Constants.Credible,
        Constants.Cynique,
    };
}
