using FrenchAdjectives.AllConstants;

namespace FrenchAdjectives.AllAdjectiveRepository;

internal static partial class AdjectiveRepository
{
    public static readonly IReadOnlyList<string> I = new[]
    {
        Constants.Incompetent,
        Constants.Insignifiant,
        Constants.Indifferent,
        Constants.Inviolable,
        Constants.Imbecile,
        Constants.Intermediaire,
        Constants.Impossible,
        Constants.Impuissant,
        Constants.Irrespectueux,
        Constants.Ironique,
        Constants.Immortel,
        Constants.Interdit,
        Constants.Impermeable,
        Constants.Iconique,
        Constants.Incontournable,
        Constants.Inedit,
        Constants.Inattendu,
        Constants.Inconnu,
        Constants.Inutile,
        Constants.Innocent,
        Constants.Invisible,
        Constants.Infernal,
        Constants.Impressionnant,
        Constants.Inhabituel,
        Constants.Inintelligible,
        Constants.Insupportable,
        Constants.Incapable,
        Constants.Inoffensif,
        Constants.Ideal,
        Constants.Important,
        Constants.Illegitime,
        Constants.Intelligent,
        Constants.Interessant,
        Constants.Improbable,
        Constants.Isole,
        Constants.Impeccable,
        Constants.Imposant,
        Constants.Incroyable,
        Constants.Indispensable,
        Constants.Inoubliable,
        Constants.Insolite,
        Constants.Inspirant,
        Constants.Intense,
        Constants.Intriguant,
        Constants.Invincible,
        Constants.Irresistible,
        Constants.Irritable,
        Constants.Immateriel,
        Constants.Incassable,
    };
}
