using FrenchAdjectives.AllConstants;

namespace FrenchAdjectives.AllAdjectiveRepository;

internal static partial class AdjectiveRepository
{
    public static readonly IReadOnlyList<string> M = new[]
    {
        Constants.Morose,
        Constants.Mineure,
        Constants.Majeure,
        Constants.Maudit,
        Constants.Meconnaissable,
        Constants.Malsaine,
        Constants.Minimal,
        Constants.Mortel,
        Constants.Moribond,
        Constants.Meconnu,
        Constants.Mince,
        Constants.Muet,
        Constants.Moindre,
        Constants.Meme,
        Constants.Macho,
        Constants.Medical,
        Constants.Majeur,
        Constants.Mechant,
        Constants.Mignon,
        Constants.Moderne,
        Constants.Mouille,
        Constants.Mysterieux,
        Constants.Magnifique,
        Constants.Majestueux,
        Constants.Memorable,
        Constants.Minuscule,
        Constants.Monumental,
        Constants.Magique,
        Constants.Mexicain,
        Constants.Maladif,
        Constants.Malade,
        Constants.Malicieux,
        Constants.Malleable,
        Constants.Melancolique,
        Constants.Meticuleux,
        Constants.Miserable,
        Constants.Mefiant,
        Constants.Mordant,
        Constants.Meritant,
        Constants.Minutieux,
        Constants.Methodique,
        Constants.Menacant,
        Constants.Mediocre,
        Constants.Modeste,
        Constants.Mobile,
        Constants.Muscle,
    };

    public static readonly IReadOnlyList<string> M_Popular = new[]
    {
        Constants.Magnifique,
        Constants.Mechant,
        Constants.Mignon,
        Constants.Moderne,
        Constants.Mysterieux,
        Constants.Modeste,
        Constants.Miserable,
        Constants.Melancolique,
        Constants.Malade,
        Constants.Malicieux,
        Constants.Menacant,
        Constants.Mediocre,
        Constants.Memorable,
        Constants.Majestueux,
        Constants.Meticuleux,
        Constants.Mefiant,
        Constants.Minutieux,
        Constants.Methodique,
        Constants.Mordant,
        Constants.Magique,
    };
}
