using FrenchAdjectives.AllConstants;

namespace FrenchAdjectives.AllAdjectiveRepository;

internal static partial class AdjectiveRepository
{
    public static readonly IReadOnlyList<string> E = new[]
    {
        Constants.Eternel,
        Constants.Encombrant,
        Constants.Emblematique,
        Constants.Entetante,
        Constants.Extreme,
        Constants.Environnant,
        Constants.Egale,
        Constants.Energique,
        Constants.Enorme,
        Constants.Ecrit,
        Constants.Excite,
        Constants.Excitee,
        Constants.Epais,
        Constants.Etrange,
        Constants.Evident,
        Constants.Excellent,
        Constants.Exotique,
        Constants.Extraordinaire,
        Constants.Exuberant,
        Constants.Elegant,
        Constants.Electrique,
        Constants.Emouvant,
        Constants.Enchanteur,
        Constants.Ensoleille,
        Constants.Enthousiaste,
        Constants.Ephemere,
        Constants.Equitable,
        Constants.Essentiel,
        Constants.Esthetique,
        Constants.Ethique,
        Constants.Etonnant,
        Constants.Euphorique,
        Constants.Evocateur,
        Constants.Extravagant,
        Constants.Espagnol,
        Constants.Excessif,
        Constants.Eclaire,
        Constants.Eclatant,
        Constants.Efficace,
        Constants.Effrayant,
        Constants.Elabore,
        Constants.Embarrassant,
        Constants.Eminent,
        Constants.Empathique,
        Constants.Endurant,
        Constants.Engage,
        Constants.Envieux,
        Constants.Epuisant,
        Constants.Equilibre,
        Constants.Erudit,
        Constants.Estimable,
    };
}
